//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public books()
        {
            this.borrows = new HashSet<borrows>();
        }
    
        public int bookId { get; set; }
        public string name { get; set; }
        public Nullable<int> pagecount { get; set; }
        public Nullable<int> point { get; set; }
        public Nullable<int> authorId { get; set; }
        public Nullable<int> typeId { get; set; }
    
        public virtual authors authors { get; set; }
        public virtual types types { get; set; }
        public virtual ICollection<borrows> borrows { get; set; }
    }
}
